-- 01_build_ies_course_aggregates.sql
-- Purpose: Aggregate course-level public census data to institution-year level.

CREATE TABLE CURSOS_MEDIDAS_AGRUPADO_IES AS
SELECT
    a.CO_IES,
    a.NU_ANO_CENSO,
    a.TP_ORGANIZACAO_ACADEMICA,
    a.TP_CATEGORIA_ADMINISTRATIVA,
    SUM(a.QT_CURSO) AS QT_CURSO,
    CASE
        WHEN SUM(CASE WHEN a.TP_MODALIDADE_ENSINO = 1 THEN a.QT_CURSO ELSE 0 END) <> 0
         AND SUM(CASE WHEN a.TP_MODALIDADE_ENSINO = 2 THEN a.QT_CURSO ELSE 0 END) <> 0 THEN 'IES HIBRIDA'
        WHEN SUM(CASE WHEN a.TP_MODALIDADE_ENSINO = 1 THEN a.QT_CURSO ELSE 0 END) <> 0 THEN 'IES PRESENCIAL'
        WHEN SUM(CASE WHEN a.TP_MODALIDADE_ENSINO = 2 THEN a.QT_CURSO ELSE 0 END) <> 0 THEN 'IES EAD'
        ELSE 'VERIFICAR'
    END AS credenciamento,
    SUM(CASE WHEN a.TP_MODALIDADE_ENSINO = 1 THEN a.QT_CURSO ELSE 0 END) AS QT_CURSO_PRES,
    SUM(CASE WHEN a.TP_MODALIDADE_ENSINO = 2 THEN a.QT_CURSO ELSE 0 END) AS QT_CURSO_EAD,
    SUM(a.QT_VG_TOTAL) AS QT_VG_TOTAL,
    SUM(a.QT_VG_TOTAL_PRESENCIAL) AS QT_VG_TOTAL_PRESENCIAL,
    SUM(a.QT_VG_TOTAL_EAD) AS QT_VG_TOTAL_EAD,
    SUM(a.QT_MAT) AS QT_MAT,
    SUM(a.QT_MAT_PRESENCIAL) AS QT_MAT_PRESENCIAL,
    SUM(a.QT_MAT_EAD) AS QT_MAT_EAD,
    SUM(a.QT_INSCRITO_TOTAL) AS QT_INSCRITO_TOTAL,
    SUM(a.QT_INSCRITO_TOTAL_PRESENCIAL) AS QT_INSCRITO_TOTAL_PRESENCIAL,
    SUM(a.QT_INSCRITO_TOTAL_EAD) AS QT_INSCRITO_TOTAL_EAD,
    SUM(a.QT_ING) AS QT_ING,
    SUM(a.QT_ING_PRESENCIAL) AS QT_ING_PRESENCIAL,
    SUM(a.QT_ING_EAD) AS QT_ING_EAD,
    SUM(a.QT_CONC) AS QT_CONC,
    SUM(a.QT_CONC_PRESENCIAL) AS QT_CONC_PRESENCIAL,
    SUM(a.QT_CONC_EAD) AS QT_CONC_EAD,
    SUM(a.QT_SIT_TRANCADA) AS QT_SIT_TRANCADA,
    SUM(CASE WHEN a.TP_MODALIDADE_ENSINO = 1 THEN a.QT_SIT_TRANCADA ELSE 0 END) AS QT_SIT_TRANCADA_PRES,
    SUM(CASE WHEN a.TP_MODALIDADE_ENSINO = 2 THEN a.QT_SIT_TRANCADA ELSE 0 END) AS QT_SIT_TRANCADA_EAD,
    SUM(a.QT_SIT_DESVINCULADO) AS QT_SIT_DESVINCULADO,
    SUM(CASE WHEN a.TP_MODALIDADE_ENSINO = 1 THEN a.QT_SIT_DESVINCULADO ELSE 0 END) AS QT_SIT_DESVINCULADO_PRES,
    SUM(CASE WHEN a.TP_MODALIDADE_ENSINO = 2 THEN a.QT_SIT_DESVINCULADO ELSE 0 END) AS QT_SIT_DESVINCULADO_EAD,
    SUM(a.QT_SIT_FALECIDO) AS QT_SIT_FALECIDO,
    SUM(CASE WHEN a.TP_MODALIDADE_ENSINO = 1 THEN a.QT_SIT_FALECIDO ELSE 0 END) AS QT_SIT_FALECIDO_PRES,
    SUM(CASE WHEN a.TP_MODALIDADE_ENSINO = 2 THEN a.QT_SIT_FALECIDO ELSE 0 END) AS QT_SIT_FALECIDO_EAD,
    SUM(a.QT_MAT_PROCESCPUBLICA) AS QT_MAT_PROCESCPUBLICA,
    SUM(a.QT_MAT_APOIO_SOCIAL) AS QT_MAT_APOIO_SOCIAL,
    SUM(a.QT_MAT_ATIV_EXTRACURRICULAR) AS QT_MAT_ATIV_EXTRACURRICULAR,
    igc.igc_continuo
FROM EXT_TB_IES_CURSOS_BR a
LEFT JOIN EXT_TB_IES_IGC_BR igc
    ON igc.ano_igc = a.NU_ANO_CENSO
   AND igc.cod_ies = a.CO_IES
GROUP BY
    a.CO_IES,
    a.NU_ANO_CENSO,
    a.TP_ORGANIZACAO_ACADEMICA,
    a.TP_CATEGORIA_ADMINISTRATIVA;
