-- 02_build_ies_poles_support.sql
-- Purpose: Estimate campus/pole footprint by institution-year.

CREATE TABLE SUBQUERY_CURSOS_POLOS AS
SELECT
    CO_IES,
    NU_ANO_CENSO,
    CASE WHEN COUNT(DISTINCT CO_MUNICIPIO) > 1 THEN 1 ELSE 0 END AS polos_ies,
    COUNT(DISTINCT CO_MUNICIPIO) AS num_polos_ies,
    COUNT(DISTINCT CASE WHEN TP_MODALIDADE_ENSINO = 1 THEN CO_MUNICIPIO END) AS num_polos_presencial,
    COUNT(DISTINCT CASE WHEN TP_MODALIDADE_ENSINO = 2 THEN CO_MUNICIPIO END) AS num_polos_ead,
    CASE
        WHEN COUNT(DISTINCT CASE WHEN TP_MODALIDADE_ENSINO = 1 THEN CO_MUNICIPIO END)
           + COUNT(DISTINCT CASE WHEN TP_MODALIDADE_ENSINO = 2 THEN CO_MUNICIPIO END)
           = COUNT(DISTINCT CO_MUNICIPIO)
            THEN 0
        ELSE COUNT(DISTINCT CASE WHEN TP_MODALIDADE_ENSINO = 1 THEN CO_MUNICIPIO END)
           + COUNT(DISTINCT CASE WHEN TP_MODALIDADE_ENSINO = 2 THEN CO_MUNICIPIO END)
           - COUNT(DISTINCT CO_MUNICIPIO)
    END AS num_polos_hibrido
FROM EXT_TB_IES_CURSOS_BR
GROUP BY CO_IES, NU_ANO_CENSO;
