-- 03_build_tsg_lagged_entrants_support.sql
-- Purpose: Compute lagged entrants used in graduation success rate calculations.

CREATE TABLE SUBQUERY_INGRESSANTES_TSG2 AS
WITH ingressos_anos_anteriores AS (
    SELECT
        CO_IES,
        NU_ANO_CENSO,
        SUM(CASE WHEN TP_GRAU_ACADEMICO IN (1, 2) THEN QT_ING ELSE 0 END) AS QT_ING_1_2,
        SUM(CASE WHEN TP_GRAU_ACADEMICO = 3 THEN QT_ING ELSE 0 END) AS QT_ING_3,
        SUM(CASE WHEN TP_GRAU_ACADEMICO = 4 THEN QT_ING ELSE 0 END) AS QT_ING_4
    FROM EXT_TB_IES_CURSOS_BR
    WHERE TP_NIVEL_ACADEMICO = '1'
      AND TP_GRAU_ACADEMICO IS NOT NULL
    GROUP BY CO_IES, NU_ANO_CENSO
)
SELECT
    a.CO_IES,
    a.NU_ANO_CENSO,
    COALESCE(b.QT_ING_1_2, 0) AS QT_ING_ANOS_ANTES_1_2,
    COALESCE(b.QT_ING_3, 0) AS QT_ING_ANOS_ANTES_3,
    COALESCE(b.QT_ING_4, 0) AS QT_ING_ANOS_ANTES_4,
    COALESCE(b.QT_ING_1_2, 0) + COALESCE(b.QT_ING_3, 0) + COALESCE(b.QT_ING_4, 0) AS QT_ING_ANOS_ANTES
FROM EXT_TB_IES_CURSOS_BR a
LEFT JOIN ingressos_anos_anteriores b
    ON a.CO_IES = b.CO_IES
   AND a.NU_ANO_CENSO = b.NU_ANO_CENSO + CASE
        WHEN a.TP_GRAU_ACADEMICO IN (1, 2) THEN 4
        WHEN a.TP_GRAU_ACADEMICO = 3 THEN 2
        WHEN a.TP_GRAU_ACADEMICO = 4 THEN 4
    END
WHERE a.TP_NIVEL_ACADEMICO = '1'
  AND a.TP_GRAU_ACADEMICO IS NOT NULL
  AND a.TP_GRAU_ACADEMICO <> 0
GROUP BY a.CO_IES, a.NU_ANO_CENSO;
